### ISSUE TITLE
Nova-components folder

### ISSUE THREAD

**Issue by new-user-name** [jexme/nova-yandex-map-coordionate-picker#1]
Hi, it's a question, not an issue.

After installation all works great. I tried to change a few things and some problems arise.
1) There is nothing in nova-components folder. Tyler says in Nova manual that newly created custom fields should reside in this folder, and they are. So where I have to make changes in your code?..

2) If I try to compile your source in vendor, the path 
import DefaultButton from "../../../vendor/laravel/nova/resources/js/components/Buttons/DefaultButton";
seems to be too short, the proper folder is
import DefaultButton from "../../../../../../vendor/laravel/nova/resources/js/components/Buttons/DefaultButton";

So I decided everything works fine because you ship with compiled js.
But maybe I'm stacking mistakes and the whole picture is completely different.

Thanks a lot for life-saving package...

**Comment by jexme** [comment]
only those files are placed in the nova-components folder that are not taken out by a separate package like this one, that is, roughly speaking, there is a monolithic application there. If you want to change the package for yourself, then you can fork and change it locally by replacing the package in `composer.json` with the local one https://getcomposer.org/doc/05-repositories.md#path
