### ISSUE TITLE
Работает, однако в консоли неверный ключ, пишет.

### ISSUE THREAD

**Issue by ghost** [jexme/nova-yandex-map-coordionate-picker#3]
`(Yandex Maps JS API): Invalid API key`
Однако работает пикер.

Я прошу в инструкции по интеграции указать шаги со стороны яндекса, куда зайти и **какой** тип ключа выбрать.
Там нынче разные ключи и не понятно какой из, по смыслу подходящих, выбрать.
В любом случае ни один не валидируется и консоль ругается на ключ.

**Comment by jexme** [comment]
Документация: https://yandex.ru/dev/jsapi30/doc/ru/#get-api-key
